files: |
    ^src/|
    ^tests/|
repos:
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.2.2
    hooks:
    - id: nbqa-black
    - id: nbqa-isort
      args: [ --profile=black, --project=pandas_profiling ]
    - id: nbqa-pyupgrade
      args: [ --py36-plus ]
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
    -   id: pyupgrade
        args: ['--py37-plus','--exit-zero-even-if-changed']
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        files: '.*'
        args: [ --profile=black, --project=pandas_profiling ]
-   repo: https://github.com/mgedmin/check-manifest
    rev: "0.47"
    hooks:
    -   id: check-manifest
-   repo: https://github.com/PyCQA/flake8
    rev: "4.0.1"
    hooks:
    -   id: flake8
        args: [ "--ignore=E203,E501,W291,W503,SFS301,SIM106" ]
        additional_dependencies:
          - flake8-comprehensions
          - flake8-sfs
          - flake8-simplify
          - flake8-eradicate
          - flake8-print
-   repo: https://github.com/PyCQA/flake8
    rev: "4.0.1"
    hooks:
    -   id: flake8
        name: flake8-annotations
        args: [ "--select=ANN001,ANN201,ANN202,ANN205,ANN206,ANN301" ]
        additional_dependencies:
          - flake8-annotations
        exclude: |
          (?x)(
            ^tests/|
            ^docsrc/|
            ^src/pandas_profiling/utils/common.py|
            ^src/pandas_profiling/utils/imghdr_patch.py
          )
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    -   id: blacken-docs
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    -   id: rst-backticks
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.931'
    hooks:
    -   id: mypy
        additional_dependencies:
          - types-requests
          - types-python-dateutil
          - types-PyYAML
          - types-setuptools
-   repo: https://github.com/sbrugman/tryceratops
    rev: v0.6.0
    hooks:
      - id: tryceratops
        args: ["-i", "TC003","--autofix"]
-   repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout

ci:
  autoupdate_commit_msg: 'ci: pre-commit-config update'
  autofix_prs: false
  autofix_commit_msg: 'ci: pre-commit auto fixes'
