repos:
-   repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 0.4.0
    hooks:
    - id: nbqa-black
      additional_dependencies: [ black==20.8b1 ]
      args: [--nbqa-mutate ]
    - id: nbqa-isort
      additional_dependencies: [ isort==5.6.4 ]
      args: [ --nbqa-mutate, --profile=black, --project=pandas_profiling ]
    - id: nbqa-pyupgrade
      additional_dependencies: [ pyupgrade==2.7.3 ]
      args: [ --nbqa-mutate, --py36-plus ]
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.7.3
    hooks:
    -   id: pyupgrade
        args: ['--py36-plus','--exit-zero-even-if-changed']
-   repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
      - id: isort
        files: '.*'
        args: [ --profile=black, --project=pandas_profiling ]
-   repo: https://github.com/mgedmin/check-manifest
    rev: "0.45"
    hooks:
    -   id: check-manifest
