[tool.pytest.ini_options]
markers =  ["sparktest"]
[tool.pytest.ini_options.spark_options]
"spark.executor.id" = "driver"
"spark.app.name" = "PySparkShell"
"spark.executor.instances" = 1
"master" = "local[*]"
"spark.sql.catalogImplementation" = "in-memory"
"spark.driver.host" = "127.0.0.1"
"spark.driver.bindAddress" = "127.0.0.1"