name: Merge into master branch


on:
  push:
    branches: 
    - master


jobs:
  prepare:
    name: Calculate Version and Build Number
    runs-on: ubuntu-22.04

    outputs:
      build_number: ${{ steps.build_number.outputs.value }}
      new_release: ${{ steps.semantic.outputs.new_release_published }}
      release: v${{ steps.semantic.outputs.new_release_version }}
      release_notes: ${{ steps.semantic.outputs.new_release_notes }}
      version: v${{ steps.version.outputs.value }}

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.ACCESS_TOKEN }}

    - uses: cycjimmy/semantic-release-action@v3
      id: semantic
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        branch: master
        dry_run: true

    - name: Count number or releases for tag
      id: build_number
      run: echo "value=$(($(git tag | grep -c ${{ steps.semantic.outputs.new_release_version }}.rc) + 1))" >> $GITHUB_OUTPUT

    - name: Compute version
      id: version
      run: echo "value=${{ steps.semantic.outputs.new_release_version }}.rc${{ steps.build_number.outputs.value }}" >> $GITHUB_OUTPUT


  prerelease-tag:
    if: needs.prepare.outputs.new_release == 'true'

    name: Create Prerelease Tag
    runs-on: ubuntu-22.04

    needs:
    - prepare

    steps:
    - uses: ydataai/create-tag@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        tag: ${{ needs.prepare.outputs.version }}
        message: ${{  github.event.head_commit.message }}


  draft-release:
    if: needs.prepare.outputs.new_release == 'true'

    name: Draft Release
    runs-on: ubuntu-22.04

    needs:
    - prepare

    steps:
    - name: Delete Previous drafts
      uses: hugo19941994/delete-draft-releases@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    - name: Create Draft Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
        tag_name: ${{ needs.prepare.outputs.release }}
        release_name: ${{ needs.prepare.outputs.release }}
        body: ${{ needs.prepare.outputs.release_notes }}
        draft: true
        commitish: master

